name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: ''

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t cloud-usage .

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Test Application
        run: docker-compose exec cloud-usage curl -X GET http://localhost:8080/calculate-usage